sudo: required
language: node_js
python:
- '3.7'
stages:
- name: test
#services:
#- docker
before_install:
install:
- pip install -r requirements.txt
- curl -sL https://deb.nodesource.com/setup_12.x | bash
- sudo apt-get update
- sudo apt-get install -y nodejs
- npm i -g @dvcorg/cml
- sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libfontconfig-dev
- npm install -g vega-cli vega-lite
jobs:
  include:
  - stage: test
    script:
    - python train.py
    - echo "## Model Metrics" >> report.md
    - cat metrics.txt >> report.md
    - cml-send-comment report.md
