sudo: required
language: python
python:
- '3.7'
stages:
- name: test
services:
- docker

before_install:
  - docker pull dvcorg/cml:0-dvc2-base1-gpu

install:
- pip install -r requirements.txt
#- sudo apt-get update
#- nvm install --lts
#- npm i -g @dvcorg/cml
#- sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libfontconfig-dev
#- npm install -g vega-cli vega-lite

before_script:
#- docker pull dvcorg/cml:0-dvc2-base1-gpu

jobs:
  include:
  - stage: test
    script:
    - docker run dvcorg/cml:0-dvc2-base1-gpu /bin/sh -c "pwd"
#    - docker run dvcorg/cml:0-dvc2-base1-gpu /bin/sh -c "python train.py"
#    - docker ps -a
#    - docker run dvcorg/cml:0-dvc2-base1-gpu /bin/sh -c "echo "## Model Metrics" >> report.md"
#    - docker run dvcorg/cml:0-dvc2-base1-gpu /bin/sh -c "cat metrics.txt >> report.md"
#    - docker run dvcorg/cml:0-dvc2-base1-gpu /bin/sh -c "echo "## Data Viz" >> report.md"
#    - docker run dvcorg/cml:0-dvc2-base1-gpu /bin/sh -c "cml-publish feature_importance.png --md >> report.md"
#    - docker run dvcorg/cml:0-dvc2-base1-gpu /bin/sh -c "cml-send-comment report.md"
#    - python train.py
#    - echo "## Model Metrics" >> report.md
#    - cat metrics.txt >> report.md
#    - echo "## Data Viz" >> report.md
#    - cml-publish feature_importance.png --md >> report.md
#    - cml-publish residuals.png --md >> report.md
#    - cml-send-comment report.md
