sudo: required
language: python
python:
- '3.7'
stages:
- name: test
#services:
#- docker
before_install:
install:
- pip install -r requirements.txt
- npm i -g @dvcorg/cml
jobs:
  include:
  - stage: test
    script:
    - python train.py
    - echo "## Model Metrics" >> report.md
    - cat metrics.txt >> report.md
    - cml-send-comment report.md
